version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  prod-server:
    build:
      dockerfile: prod-server/Dockerfile
      context: ./
    ports:
      - "80:80"
      - "443:443"