version: '3'

services:
  database:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env.dev

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=database # Ensures Postgres connects properly when running locally or via docker-compose

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - REACT_APP_FASTAPI_URL=https://127.0.0.1:8000