version: '3'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env.prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  prod-server:
    ports:
      - "80:80"
      - "443:443"
    image: vaultmaster-prod-server