version: '3'

services:
  database:
    image: postgres:15.4
    ports:
      - "5432:5432"
    env_file:
      - .env.dev
    volumes:
      - ./database/healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: ["CMD-SHELL", "/healthcheck.sh"]
      interval: 4s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=database

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    environment:
      - REACT_APP_FASTAPI_URL=http://127.0.0.1:8000