version: '3'

services:
  backend:
    build:
      context: ./backend
    env_file:
      - .env.prod
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  prod-server:
    ports:
      - "80:80"
      - "443:443"
    image: vaultmaster-prod-server
    volumes:
      - prod-server/.well-known:/usr/share/nginx/html/.well-known # SSL verification (via HTTP)
      - prod-server/ssl:/etc/nginx/ssl # SSL certificates