"""Migration message

Revision ID: 32b25d83bd9f
Revises: 5a4d7debcdfb
Create Date: 2023-11-03 23:45:08.976135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b25d83bd9f'
down_revision: Union[str, None] = '5a4d7debcdfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('fernet_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential', 'fernet_key')
    # ### end Alembic commands ###
