"""Migration message

Revision ID: 5a4d7debcdfb
Revises: f0ad565e4ee8
Create Date: 2023-11-03 23:27:21.916678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a4d7debcdfb'
down_revision: Union[str, None] = 'f0ad565e4ee8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('fernet_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential', 'fernet_key')
    # ### end Alembic commands ###
