"""Migration message

Revision ID: 7516e23a1ef7
Revises: cd11fcf8b0cc
Create Date: 2023-11-11 01:53:26.689312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7516e23a1ef7'
down_revision: Union[str, None] = 'cd11fcf8b0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
