"""Migration message

Revision ID: 7f0320072bad
Revises: d03b858d19da
Create Date: 2023-11-06 17:15:23.842676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0320072bad'
down_revision: Union[str, None] = 'd03b858d19da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('fernet_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential', 'fernet_key')
    # ### end Alembic commands ###
