"""Migration message

Revision ID: d03b858d19da
Revises: 32b25d83bd9f
Create Date: 2023-11-06 17:14:12.665044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd03b858d19da'
down_revision: Union[str, None] = '32b25d83bd9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('fernet_key', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credential', 'fernet_key')
    # ### end Alembic commands ###
