"""MESSAGE

Revision ID: f58c33bcc42d
Revises: e2dffb021d7a
Create Date: 2023-10-31 17:02:36.991103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f58c33bcc42d'
down_revision: Union[str, None] = 'e2dffb021d7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('note', sa.Text(), nullable=True))
    op.drop_column('credential', 'node')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credential', sa.Column('node', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('credential', 'note')
    # ### end Alembic commands ###
